@file:androidx.annotation.OptIn(androidx.media3.common.util.UnstableApi::class)

package xyz.libravault.feature.player.service

import android.annotation.SuppressLint
import android.app.PendingIntent
import android.util.Log
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.session.CommandButton
import androidx.media3.session.MediaSession
import androidx.media3.session.MediaSessionService
import dagger.hilt.android.AndroidEntryPoint
import javax.inject.Inject

/**
 * Foreground [MediaSessionService] — keeps audio playing when backgrounded or screen locked.
 *
 * Notification buttons are auto-generated by [LibravaultNotificationProvider] which
 * publishes a five-button compact strip to the Android 13+ system media tile
 * (lockscreen "Live notifications" / Quick-Settings media output):
 * `[ Prev | −N s | Play/Pause | +N s | Next ]`, where `N` is the user's
 * `defaultSkipDurationSec` preference (default 30 s). See the provider class for
 * details and the documented runtime-increment limitation.
 *
 * ## Custom layout — required for the system media tile
 *
 * The lockscreen "Live notifications" card and the Quick-Settings media output
 * panel read directly from the `MediaSession`'s custom layout (Android 13+
 * forwards `PlaybackStateCompat.customActions` from there, not from the
 * notification's compact-view indices). Without an explicit custom layout,
 * the system falls back to a minimal 2-button default that exposes only
 * `COMMAND_PLAY_PAUSE` and one of the seek commands — that's the exact
 * "only << and ▶" symptom users reported after the previous fix shipped.
 *
 * `MediaSession.Builder.setCustomLayout(...)` is called here with the same
 * 5-button strip that the notification uses, so the two surfaces stay in
 * sync. Each button's `isEnabled` is rewritten per-controller by the session
 * based on the actual `Player.Commands` available — taps on a disabled
 * prev/next (single-track audiobook playlist) are no-op'd by ExoPlayer.
 *
 * The seek increment is seeded from `defaultSkipDurationSec` on the ExoPlayer
 * singleton in [PlayerModule] when the player is first built; in-app ± buttons in
 * the reader and library mini-players read the preference live and therefore always
 * honor runtime updates without restarting the service.
 */
@AndroidEntryPoint
class PlaybackService : MediaSessionService() {

    private var mediaSession: MediaSession? = null

    @Inject
    lateinit var player: ExoPlayer

    @SuppressLint("UnsafeOptInUsageError")
    override fun onCreate() {
        super.onCreate()
        Log.i(TAG, "onCreate: start")
        try {
            setMediaNotificationProvider(LibravaultNotificationProvider(this))
            Log.i(TAG, "onCreate: notification provider set")
        } catch (t: Throwable) {
            Log.e(TAG, "onCreate: setMediaNotificationProvider threw", t)
            // Fall back to Media3's default notification layout. This is non-fatal —
            // playback works correctly without the custom compact-strip configuration.
        }

        val sessionActivity = packageManager
            .getLaunchIntentForPackage(packageName)
            ?.let { intent ->
                PendingIntent.getActivity(
                    this, 0, intent,
                    PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT,
                )
            }

        val builder = MediaSession.Builder(this, player)
        Log.i(TAG, "onCreate: builder constructed, sessionActivity not null=${sessionActivity != null}")

        sessionActivity?.let { builder.setSessionActivity(it) }

        // Publish the 5-button strip to the system media tile (lockscreen +
        // Quick Settings media output). `icon = null` here — for the
        // MediaSession surface we let the system supply the default icon for
        // each predefined `Player.COMMAND_*`; the notification path uses the
        // same builder with explicit bitmap icons via `LibravaultNotificationProvider`.
        val standardStrip: List<CommandButton> = try {
            LibravaultNotificationProvider.buildStandardStrip(
                context = this,
                showPauseButton = player.playWhenReady,
            ).also { Log.i(TAG, "onCreate: buildStandardStrip produced ${it.size} buttons") }
        } catch (t: Throwable) {
            Log.e(TAG, "onCreate: buildStandardStrip threw; continuing without customLayout", t)
            emptyList()
        }
        if (standardStrip.isNotEmpty()) builder.setCustomLayout(standardStrip)

        try {
            mediaSession = builder.build()
            Log.i(TAG, "onCreate: MediaSession built; id=${mediaSession?.id}")
        } catch (t: Throwable) {
            Log.e(TAG, "onCreate: MediaSession.Builder.build() threw", t)
            throw t
        }
    }

    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession? {
        val session = mediaSession
        Log.i(
            TAG,
            "onGetSession: pkg=${controllerInfo.packageName} " +
                "interfaceVersion=${controllerInfo.interfaceVersion} " +
                "sessionNotNull=${session != null} " +
                "isMediaNotification=${session?.isMediaNotificationController(controllerInfo)}",
        )
        return session
    }

    override fun onDestroy() {
        Log.i(TAG, "onDestroy")
        mediaSession?.run {
            release()
            // Do NOT release the singleton ExoPlayer here — it is @Singleton scoped
            // and shared with SleepTimer for volume fade-out. Releasing it would
            // cause IllegalStateException("Player is released") on any subsequent
            // sleep timer operation or new PlayerViewModel instance.
        }
        mediaSession = null
        super.onDestroy()
    }

    private companion object {
        const val TAG = "LibravaultPlayback"
    }
}
