@file:androidx.annotation.OptIn(androidx.media3.common.util.UnstableApi::class)

package xyz.libravault.feature.player.service

import android.annotation.SuppressLint
import android.app.PendingIntent
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.session.MediaSession
import androidx.media3.session.MediaSessionService
import dagger.hilt.android.AndroidEntryPoint
import javax.inject.Inject

/**
 * Foreground [MediaSessionService] — keeps audio playing when backgrounded or screen locked.
 *
 * Notification buttons are auto-generated by [LibravaultNotificationProvider] which
 * publishes a five-button compact strip to the Android 13+ system media tile
 * (lockscreen "Live notifications" / Quick-Settings media output):
 * `[ Prev | −N s | Play/Pause | +N s | Next ]`, where `N` is the user's
 * `defaultSkipDurationSec` preference (default 30 s). See the provider class for
 * details and the documented runtime-increment limitation.
 *
 * The seek increment is seeded from `defaultSkipDurationSec` on the ExoPlayer
 * singleton in [PlayerModule] when the player is first built; in-app ± buttons in
 * the reader and library mini-players read the preference live and therefore always
 * honor runtime updates without restarting the service.
 */
@AndroidEntryPoint
class PlaybackService : MediaSessionService() {

    private var mediaSession: MediaSession? = null

    @Inject
    lateinit var player: ExoPlayer

    @SuppressLint("UnsafeOptInUsageError")
    override fun onCreate() {
        super.onCreate()
        try {
            setMediaNotificationProvider(LibravaultNotificationProvider(this))
        } catch (_: Exception) {
            // Fall back to Media3's default notification layout. This is non-fatal —
            // playback works correctly without the custom compact-strip configuration.
        }

        val sessionActivity = packageManager
            .getLaunchIntentForPackage(packageName)
            ?.let { intent ->
                PendingIntent.getActivity(
                    this, 0, intent,
                    PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT,
                )
            }

        val builder = MediaSession.Builder(this, player)

        sessionActivity?.let { builder.setSessionActivity(it) }
        mediaSession = builder.build()
    }

    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession? =
        mediaSession

    override fun onDestroy() {
        mediaSession?.run {
            release()
            // Do NOT release the singleton ExoPlayer here — it is @Singleton scoped
            // and shared with SleepTimer for volume fade-out. Releasing it would
            // cause IllegalStateException("Player is released") on any subsequent
            // sleep timer operation or new PlayerViewModel instance.
        }
        mediaSession = null
        super.onDestroy()
    }
}
