org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=2
org.gradle.daemon.idletimeout=600000
kotlin.daemon.jvmargs=-Xmx2g
kotlin.code.style=official
ksp.incremental=true
ksp.incremental.intermodule=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=35
